config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  get "pages/home"
  get "pages/login"

  get "home", to: "pages#home"
  get "login", to: "pages#login"

  resources :tags,
    except: :destroy do
    member do
      get :posts,
        except: :destroy
    end
  end

  resources :forums,
    except: :destroy do
      member do
        put :fake_delete
        get :join, :leave, :cancel
      end

      resources :posts,
        except: :destroy,
        controller: :forum_posts do
        member do
          put :fake_delete
        end
      end

      resources :users,
        except: :destroy, 
        controller: :forums do
          member do
            put :bucket, :confirm_join, :pend
        end
      end
  end

  resources :users do
    resources :posts,
      controller: :user_posts,
      except: :destroy
  end

  resources :posts, 
    except: :destroy do
      resources :tags,
        controller: :post_tags,
        except: :destroy
      resources :replies,
        controller: :post_replies,
        except: :destroy
      member do
        put :fake_delete
      end
  end

  resource :session,
    only: [:create, :destroy]

  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  validates :name, 
    :presence => {:message => "不能空白"},
    :length => {minimum: 2, maximum: 20, :message => "長度不正確"},
    :uniqueness => true

  # public for everyone, private for people in forum, deleted for been fake_deleted
  validates :status, inclusion: {in: ['public', 'private', 'deleted']}

  has_many :posts
  has_many :forum_userships
  has_many :users, :through => :forum_userships
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :find_forum, :only => [:show, :edit, :update, :destroy, :join, :leave, :cancel, :fake_delete, :check_joi, :kick_out]

  def index
    @forums = Forum.all.where("status != ?", "deleted")
  end

  def show
    @joined_users = []
    @pending_users = []
    @bucketed_users = []

    ships = ForumUsership.where("forum_id = ?", @forum)
    users = User.all

    ships.each do |ship|
      case ship.status
      when "joined"
        @joined_users << users.find_by(:id => ship.user_id)
      when "pending"
        @pending_users << users.find_by(:id => ship.user_id)
      when "bucketed"
        @bucketed_users << users.find_by(:id => ship.user_id)
      end
    end
    
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new forum_params
    @forum.status = "private"
    @forum.creater_id = current_user.id
    @forum.users << current_user
    if @forum.save
      find_ship_of_forum_and_current_user
      @ship.status = "hosting"
      @ship.save
      flash[:notice] = "建立成功"
      redirect_to forums_path
    else
      flash[:alert] = "再試一次"
      render new_forum_path
    end
  end

  def edit
  end

  def update
    if @forum.update forum_params
      flash[:notice] = "看板編輯成功"
      redirect_to forum_posts_path(@forum)
    else
      flash[:alert] = "看板編輯失敗"
      render :edit
    end
  end

  def check_join
    ships = ForumUsership.where("status = ?", "pending").find_by_forum_id(@forum)
    redirect_to :check_join_forum
  end

  def join
    unless @forum.users.include? current_user
      @forum.users << current_user
    end
    find_ship_of_forum_and_current_user
    @ship.status = "pending"
    @ship.save
    flash[:notice] = "加入成功"
    redirect_to forum_posts_path(@forum)
  end

  def leave
    if @forum.users.include? current_user
      find_ship_of_forum_and_current_user
      @ship.status = "left"
      @ship.save
      #@forum.users.delete current_user
      # not really deleted :)
      flash[:notice] = "退出成功"
    else
      flash[:alert] = "退出fail"
    end
    redirect_to forum_posts_path(@forum)
  end

  def cancel
    if @forum.users.include? current_user
      @forum.users.delete current_user
    end
    flash[:notice] = "取消申請"
    redirect_to forums_path(@forum)
  end

  def fake_delete
    @forum.status = "deleted"
    @forum.posts.each do |post|
      post.status = "deleted"
      post.save
    end
    @forum.save
    flash[:notice] = "此看板及其文章皆刪除"
    redirect_to forums_path
  end

  def bucket
    set_ship_status "bucketed"
  end

  def confirm_join
    set_ship_status "joined"
  end

  def pend
    set_ship_status "pending"
  end

  def destroy
    @forum.posts.destroy_all
    @forum.destroy
    flash[:notice] = "此看板及其文章皆刪除 absolutely"
    redirect_to forums_path
  end

  protected

  def find_forum
    @forum = Forum.find(params[:id])
  end

  def forum_params
    params.require(:forum).permit(:name, :user_ids=>[])
  end

  def find_ship_of_forum_and_current_user
    @ship = ForumUsership.find_by_forum_id_and_user_id(@forum, current_user)
  end

  def set_ship_status status
    user = User.find(params[:id])
    forum = Forum.find(params[:forum_id])
    ship = ForumUsership.find_by_forum_id_and_user_id(forum, user)
    ship.status = status
    if ship.save
      redirect_to forum
    end
  end

end

app/helpers/forums_helper.rb
module ForumsHelper

  def action_link
    find_ship
    case @ship.try(:status)
    when "hosting"
      content_tag :a, link_to("編輯看板", edit_forum_path(@forum))
    when "joined"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    when "pending"
      content_tag :a, link_to("取消申請", cancel_forum_path(@forum))
    when "bucketed"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    else
      content_tag :a, link_to("加入看板", join_forum_path(@forum))
    end
  end

  def members_wanna_join
    content_tag :a, link_to("誰想加入", check_join_form_path(@forum))
  end

  def post_a_feiwen_link
    find_ship
    if @ship.try(:status) == "hosting" || @ship.try(:status) == "joined"
      content_tag :a, link_to("po 個費文", new_forum_post_path(@forum))
    end
  end

  protected

  def find_ship
    @ship = ForumUsership.find_by_forum_id_and_user_id(@forum, current_user)
  end
end

app/views/forums/_form.html.erb
<%= form_for @forum do |f| %>
  <%= f.label :name, "看板名稱: " %>
  <%= f.text_field :name, autofocus: true %><br>
  <%= f.collection_check_boxes :user_ids, User.all, :id, :name %>
  <%#= f.collection_check_boxes :user_ids, @forum.users, :id, :name %>
  <%= f.submit "送出"%>
<% end %>

app/views/forums/check_join.html.erb
"check join"

app/views/forums/index.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <% @forums.each do |forum| %>
      <%= link_to forum.name, forum_posts_path(forum) %>
      <%= forum.posts.where("status = ?", "forum").size %><br>
    <% end %>
  </div>
  <div class="panel-footer">
    <%= link_to "建立看板", new_forum_path %>
  </div>
</div>

app/views/forums/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">建立看板</div>
  <div class="panel-body">
    <%= render "form" %>
  </div>
</div>

app/views/forums/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to "#{@forum.name} 板資訊", forum_posts_path(@forum) %>
  </div>

  <div class="panel-body">
    <ul>
      <li>創板人: <%= link_to User.find(@forum.creater_id).name, user_posts_path(@forum.creater_id) %></li>
      <li>板友:</li>
      <ul>
        <% @joined_users.each do |user| %>
          <li>
            <%= link_to user.name, user_posts_path(user) %>
            <%= link_to "水桶", bucket_forum_user_path(@forum, user), method: :put %>
            <%= link_to "放到申請中", pend_forum_user_path(@forum, user), method: :put %>
          </li>
        <% end %>
      </ul>
      <li>申請加入:</li>
      <ul>
        <% @pending_users.each do |user| %>
        <li>
          <%= link_to user.name, user_posts_path(user) %>
          <%= link_to "確認加入", confirm_join_forum_user_path(@forum, user), method: :put %>
        </li>
        <% end %>
      </ul>
      <li>水桶中:</li>
        <ul>
          <% @bucketed_users.each do |user| %>
            <li>
              <%= link_to user.name, user_posts_path(user) %>
              <%= link_to "回復資格", confirm_join_forum_user_path(@forum, user), method: :put %>
            </li>
          <% end %>
        </ul>
      <ul>
      </ul>
    </ul>
  </div>
</div>