config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  get "pages/home"
  get "pages/login"

  get "home", to: "pages#home"
  get "login", to: "pages#login"

  resources :tags,
    except: :destroy do
    member do
      get :posts,
        except: :destroy
    end
  end

  resources :forums,
    except: :destroy do
      member do
        put :fake_delete
        get :join, :leave, :cancel
      end

      resources :posts,
        except: :destroy,
        controller: :forum_posts do
        member do
          put :fake_delete
        end
      end

      resources :users,
        except: :destroy, 
        controller: :forums do
          member do
            put :bucket, :confirm_join, :pend
        end
      end
  end

  resources :users do
    resources :posts,
      controller: :user_posts,
      except: :destroy
  end

  resources :posts, 
    except: :destroy do
      resources :tags,
        controller: :post_tags,
        except: :destroy
      resources :replies,
        controller: :post_replies,
        except: :destroy
      member do
        put :fake_delete
      end
  end

  resource :session,
    only: [:create, :destroy]

  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  validates :name, 
    :presence => {:message => "不能空白"},
    :length => {minimum: 2, maximum: 20, :message => "長度不正確"},
    :uniqueness => true

  # public for everyone, private for people in forum, deleted for been fake_deleted
  validates :status, inclusion: {in: ['public', 'private', 'deleted']}

  has_many :posts
  has_many :forum_userships
  has_many :users, :through => :forum_userships
end

app/models/forum_postship.rb
class ForumPostship < ActiveRecord::Base
  belongs_to :post
  belongs_to :forum
end

app/models/forum_usership.rb
class ForumUsership < ActiveRecord::Base
  validates :status, inclusion: {in: ["hosting", "joined", "pending", "bucketed", "left"]}
  belongs_to :forum
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :content, :status, presence: true
  validates :status, inclusion: {in: ['public', 'forum', 'private', 'deleted']}

  before_validation :set_content_from_title
  
  has_many :post_tagships
  has_many :tags, :through => :post_tagships
  has_many :replies
  
  belongs_to :forum
  belongs_to :user

  after_initialize :init

  def init
    self.user_id = 1 unless user_id
    #self.status = "public"
  end

  def set_content_from_title
    self.content = title if content.blank?
  end

  #scope :own_posts, -> (user) { where("user_id = ? AND status != ?", user.id, "deleted").order("updated_at DESC") }
  #scope :others_posts, -> (user) { where("user_id = ? AND status = ?", user.id, "public").order("updated_at DESC") }

  #  def title_must_start_with_x
  #    unless title.to_s.start_with? 'X'
  #      errors.add(:title, 'must start with "X"')
  #    end
  #  end
end

app/models/post_tagship.rb
class PostTagship < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tagships
  has_many :posts, :through => :post_tagships

  validates :name, presence: true
  #has_and_belongs_to_many :posts

  #@posts = @tag.posts.where(status: 'public').order("updated_at DESC")
end

app/models/user.rb
class User < ActiveRecord::Base
  
  #validates :password, length: {6..20}
  validates_presence_of :name, :email
  validates :email, uniqueness: true, on: :create
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  has_many :replies
  has_many :posts
  has_secure_password
  has_many :forum_userships
  has_many :forums, through: :forum_userships
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper

  def action_link
    find_ship
    case @ship.try(:status)
    when "hosting"
      content_tag :a, link_to("編輯看板", edit_forum_path(@forum))
    when "joined"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    when "pending"
      content_tag :a, link_to("取消申請", cancel_forum_path(@forum))
    when "bucketed"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    else
      content_tag :a, link_to("加入看板", join_forum_path(@forum))
    end
  end

  def members_wanna_join
    content_tag :a, link_to("誰想加入", check_join_form_path(@forum))
  end

  def post_a_feiwen_link
    find_ship
    if @ship.try(:status) == "hosting" || @ship.try(:status) == "joined"
      content_tag :a, link_to("po 個費文", new_forum_post_path(@forum))
    end
  end

  protected

  def find_ship
    @ship = ForumUsership.find_by_forum_id_and_user_id(@forum, current_user)
  end
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_li text, path
    active = request.path == path ? "active" : ""
    content_tag :li, link_to(text, path), class: active + " navbar-nav"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/helpers/userlink_helper.rb
module UserlinkHelper
  def user_link post, userid
    username = post.user.try(:name)
    userid ||= -1
    content_tag :a, link_to(username, userid)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>費文王</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="container-fluid">
            <%= render 'shared/navbar' %>
            <%#= render 'shared/navbar', line_number: 1%>
          </div>
        </div>
      </nav>
      <!--<div class="jumbotron">-->
      <br><br><br>
      <div class="row">
        <p style="color: green"><%= flash[:notice] %></p>
        <p style="color: red"><%= flash[:alert] %></p>
      </div>

      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-collapse collapse">
  <ul class="nav navbar-nav">
    <%= nav_li '關於本站', home_path %>
    <%= nav_li '首頁', posts_path %>
    <%= nav_li '各種看板', forums_path %>
    <%= nav_li '標籤列表', tags_path %>
    <%#= nav_li '新增標籤', new_tag_path %>
    <%#= nav_li '新增文章', new_post_path %>
    <%#= nav_li '關於', about_path %>
    <%#= nav_li '樂透', math_path %>
    <%#= nav_li '表單', form_path %>
  </ul>

  <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <%= current_user.name %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "我的費文 :D", user_posts_path(current_user) %></li>
          <li><%= link_to "個人資料", user_path(current_user) %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "登出", session_path, method: :delete %></li>
        </ul>
      </li>

      <%#= link_to current_user.name, user_posts_path(current_user) %> 
      <%#= link_to "登出", session_path, method: :delete %>
      <%#= link_to '個人資料', user_path(current_user) %>
    <% else %>
      <%= nav_li "登入", login_path %>
    <% end %>
  </ul>
</div>