config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  get "pages/home"
  get "pages/login"

  get "home", to: "pages#home"
  get "login", to: "pages#login"

  resources :tags,
    except: :destroy do
    member do
      get :posts,
        except: :destroy
    end
  end

  resources :forums,
    except: :destroy do
      member do
        put :fake_delete
        get :join, :leave, :cancel
      end

      resources :posts,
        except: :destroy,
        controller: :forum_posts do
        member do
          put :fake_delete
        end
      end

      resources :users,
        except: :destroy, 
        controller: :forums do
          member do
            put :bucket, :confirm_join, :pend
        end
      end
  end

  resources :users do
    resources :posts,
      controller: :user_posts,
      except: :destroy
  end

  resources :posts, 
    except: :destroy do
      resources :tags,
        controller: :post_tags,
        except: :destroy
      resources :replies,
        controller: :post_replies,
        except: :destroy
      member do
        put :fake_delete
      end
  end

  resource :session,
    only: [:create, :destroy]

  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  validates :name, 
    :presence => {:message => "不能空白"},
    :length => {minimum: 2, maximum: 20, :message => "長度不正確"},
    :uniqueness => true

  # public for everyone, private for people in forum, deleted for been fake_deleted
  validates :status, inclusion: {in: ['public', 'private', 'deleted']}

  has_many :posts
  has_many :forum_userships
  has_many :users, :through => :forum_userships
end

app/models/forum_postship.rb
class ForumPostship < ActiveRecord::Base
  belongs_to :post
  belongs_to :forum
end

app/models/forum_usership.rb
class ForumUsership < ActiveRecord::Base
  validates :status, inclusion: {in: ["hosting", "joined", "pending", "bucketed", "left"]}
  belongs_to :forum
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :content, :status, presence: true
  validates :status, inclusion: {in: ['public', 'forum', 'private', 'deleted']}

  before_validation :set_content_from_title
  
  has_many :post_tagships
  has_many :tags, :through => :post_tagships
  has_many :replies
  
  belongs_to :forum
  belongs_to :user

  after_initialize :init

  def init
    self.user_id = 1 unless user_id
    #self.status = "public"
  end

  def set_content_from_title
    self.content = title if content.blank?
  end

  #scope :own_posts, -> (user) { where("user_id = ? AND status != ?", user.id, "deleted").order("updated_at DESC") }
  #scope :others_posts, -> (user) { where("user_id = ? AND status = ?", user.id, "public").order("updated_at DESC") }

  #  def title_must_start_with_x
  #    unless title.to_s.start_with? 'X'
  #      errors.add(:title, 'must start with "X"')
  #    end
  #  end
end

app/models/post_tagship.rb
class PostTagship < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tagships
  has_many :posts, :through => :post_tagships

  validates :name, presence: true
  #has_and_belongs_to_many :posts

  #@posts = @tag.posts.where(status: 'public').order("updated_at DESC")
end

app/models/user.rb
class User < ActiveRecord::Base
  
  #validates :password, length: {6..20}
  validates_presence_of :name, :email
  validates :email, uniqueness: true, on: :create
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  has_many :replies
  has_many :posts
  has_secure_password
  has_many :forum_userships
  has_many :forums, through: :forum_userships
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show, :posts]
  before_action :find_tag, :only => [:show, :edit, :update, :destroy, :posts]

  def index
    @tags = Tag.all
    post_tagships = PostTagship.all
    @hits_of_each_tag = {}

    post_tagships.each do |ship|
      if @hits_of_each_tag.has_key? ship.tag_id
        @hits_of_each_tag[ship.tag_id] += 1
      else
        @hits_of_each_tag[ship.tag_id] = 1
      end
    end
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new tag_params

    begin
      @tag.save
    rescue ActiveRecord::RecordNotUnique => e
      flash[:alert] = " #{@tag.name} 早就有囉, 換一個吧 :)"
    end
    redirect_to tags_path
    #if @tag.save
    #  flash[:notice] = "新增標籤成功"
    #  redirect_to tags_path
    #else
    #  flash[:alert] = "新增標籤失敗"
    #  render :new
    #end
  end

  def edit
  end

  def update
    if @tag.update tag_params
      flash[:notice] = "編輯標籤成功"
      redirect_to tag_posts_path(@tag)
    else
      flash[:alert] = "編輯標籤失敗"
      render :edit
    end
  end

  def destroy
    PostTagship.where(:tag_id => @tag).delete_all
    @tag.destroy
    flash[:notice] = "刪除標籤成功"
    redirect_to tags_path
  end

  def posts
    @posts = @tag.posts.where("status = ? OR status != ? AND user_id = ? ", "public", "deleted", session[:user_id]).order("updated_at DESC")
    render :posts_tag
  end

  # with routes get 'tags/posts_of_this_tag'
  #def posts_of_this_tag
  #  @tag = Tag.find(params[:tag_id])
  #  @posts = @tag.posts.where("status = ? OR status != ? AND user_id = ? ", "public", "deleted", session[:user_id]).order("updated_at DESC")
  #  render :posts_of_this_tag
  #end

  def hot_tag
  end

  protected

  def find_tag
    @tag = Tag.find(params[:id])
  end

  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper

  def action_link
    find_ship
    case @ship.try(:status)
    when "hosting"
      content_tag :a, link_to("編輯看板", edit_forum_path(@forum))
    when "joined"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    when "pending"
      content_tag :a, link_to("取消申請", cancel_forum_path(@forum))
    when "bucketed"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    else
      content_tag :a, link_to("加入看板", join_forum_path(@forum))
    end
  end

  def members_wanna_join
    content_tag :a, link_to("誰想加入", check_join_form_path(@forum))
  end

  def post_a_feiwen_link
    find_ship
    if @ship.try(:status) == "hosting" || @ship.try(:status) == "joined"
      content_tag :a, link_to("po 個費文", new_forum_post_path(@forum))
    end
  end

  protected

  def find_ship
    @ship = ForumUsership.find_by_forum_id_and_user_id(@forum, current_user)
  end
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_li text, path
    active = request.path == path ? "active" : ""
    content_tag :li, link_to(text, path), class: active + " navbar-nav"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_replys_helper.rb
module PostReplysHelper
end

app/helpers/post_status_helper.rb
module PostStatusHelper
  def post_status_signal post
    case post.status
    when "public"
      return "+"
    when "private"
      return "-"
    end
  end
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/helpers/userlink_helper.rb
module UserlinkHelper
  def user_link post, userid
    username = post.user.try(:name)
    userid ||= -1
    content_tag :a, link_to(username, userid)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tags/_form.html.erb
<%= form_for tag do |f| %>
  <%= f.text_field :name %>
  <%= f.submit "新增標籤" %>
<% end %>

app/views/tags/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    編輯標籤
  </div>
  <div class="panel-body">
    <%= render 'new_form', :tag => Tag.find(params[:id]) %>
  </div>
</div>
<%#= render 'form' %>

<%#= form_for @tag do |f| %>
  <%#= f.text_field :name %>
  <%#= f.submit %>
<%# end %>

app/views/tags/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    標籤列表
  </div>
  <div class="panel-body">
    <ol>
      <% @tags.each do |tag| %>
        <li class='tag'>
          <%#= link_to tag.name, tag_posts_path(tag) %>
          <%= link_to tag.name, posts_tag_path(tag) %>
        </li>
      <% end %>
    </ol>
  </div>
  <div class="panel-footer">
    <%= render "form", :tag => Tag.new %>
  </div>
</div>

<%#= @hits_of_each_tag.inspect %>

app/views/tags/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    新增標籤
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%#= form_for @tag do |f| %>
  <%#= f.text_field :name %>
  <%#= f.submit %>
<%# end %>

app/views/tags/posts_of_this_tag.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    有
    <%= link_to @tag.name, tag_posts_path(@tag) %>
    的文章<br/>
  </div>

  <div class="panel-body">
    <ul>
      <% @posts.each do |post| %>
        <li>
          <%= link_to post.user.name, user_posts_path(post.user) %>:
          <%= link_to post.title, post %>
          <%= post_status_signal post %>
          <%= post.updated_at.to_formatted_s(:short) %>
        </li>
      <% end %>
    </ul>
  </div>
  
  <div class="panel-footer">
    <%= link_to '編輯標籤', edit_tag_path(@tag) %>
    <%= link_to '刪除標籤', tag_path(@tag), :method => :delete, :data => { :confirm => "你確定嗎?" } %>
    <%= link_to '上一頁', tags_path %>
  </div>
</div>

app/views/tags/posts_tag.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    有
    <%= link_to @tag.name, posts_tag_path(@tag) %>
    的文章<br/>
  </div>

  <div class="panel-body">
    <ul>
      <% @posts.each do |post| %>
        <li>
          <%= link_to post.user.name, user_posts_path(post.user) %>:
          <%#= link_to post.title, post %>
          <%= link_to post.title, post %>
          <%= post_status_signal post %>
          <%= post.updated_at.to_formatted_s(:short) %>
        </li>
      <% end %>
    </ul>
  </div>
  
  <div class="panel-footer">
    <%#= link_to '編輯標籤', edit_tag_path(@tag) %>
    <%#= link_to '刪除標籤', tag_path(@tag), :method => :delete, :data => { :confirm => "你確定嗎?" } %>
    <%#= link_to '上一頁', tags_path %>
  </div>
</div>

app/views/tags/show.html.erb
<%= link_to @tag.name, tag_posts_path(@tag) %>
<hr>

<%= link_to 'back', tags_path %>