config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  get "pages/home"
  get "pages/login"

  get "home", to: "pages#home"
  get "login", to: "pages#login"

  resources :tags,
    except: :destroy do
    member do
      get :posts,
        except: :destroy
    end
  end

  resources :forums,
    except: :destroy do
      member do
        put :fake_delete
        get :join, :leave, :cancel
      end

      resources :posts,
        except: :destroy,
        controller: :forum_posts do
        member do
          put :fake_delete
        end
      end

      resources :users,
        except: :destroy, 
        controller: :forums do
          member do
            put :bucket, :confirm_join, :pend
        end
      end
  end

  resources :users do
    resources :posts,
      controller: :user_posts,
      except: :destroy
  end

  resources :posts, 
    except: :destroy do
      resources :tags,
        controller: :post_tags,
        except: :destroy
      resources :replies,
        controller: :post_replies,
        except: :destroy
      member do
        put :fake_delete
      end
  end

  resource :session,
    only: [:create, :destroy]

  

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  
  validates :name, 
    :presence => {:message => "不能空白"},
    :length => {minimum: 2, maximum: 20, :message => "長度不正確"},
    :uniqueness => true

  # public for everyone, private for people in forum, deleted for been fake_deleted
  validates :status, inclusion: {in: ['public', 'private', 'deleted']}

  has_many :posts
  has_many :forum_userships
  has_many :users, :through => :forum_userships
end

app/models/forum_postship.rb
class ForumPostship < ActiveRecord::Base
  belongs_to :post
  belongs_to :forum
end

app/models/forum_usership.rb
class ForumUsership < ActiveRecord::Base
  validates :status, inclusion: {in: ["hosting", "joined", "pending", "bucketed", "left"]}
  belongs_to :forum
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :title, :content, :status, presence: true
  validates :status, inclusion: {in: ['public', 'forum', 'private', 'deleted']}

  before_validation :set_content_from_title
  
  has_many :post_tagships
  has_many :tags, :through => :post_tagships
  has_many :replies
  
  belongs_to :forum
  belongs_to :user

  after_initialize :init

  def init
    self.user_id = 1 unless user_id
    #self.status = "public"
  end

  def set_content_from_title
    self.content = title if content.blank?
  end

  #scope :own_posts, -> (user) { where("user_id = ? AND status != ?", user.id, "deleted").order("updated_at DESC") }
  #scope :others_posts, -> (user) { where("user_id = ? AND status = ?", user.id, "public").order("updated_at DESC") }

  #  def title_must_start_with_x
  #    unless title.to_s.start_with? 'X'
  #      errors.add(:title, 'must start with "X"')
  #    end
  #  end
end

app/models/post_tagship.rb
class PostTagship < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tagships
  has_many :posts, :through => :post_tagships

  validates :name, presence: true
  #has_and_belongs_to_many :posts

  #@posts = @tag.posts.where(status: 'public').order("updated_at DESC")
end

app/models/user.rb
class User < ActiveRecord::Base
  
  #validates :password, length: {6..20}
  validates_presence_of :name, :email
  validates :email, uniqueness: true, on: :create
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i

  has_many :replies
  has_many :posts
  has_secure_password
  has_many :forum_userships
  has_many :forums, through: :forum_userships
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user!, :except => [:index, :show]

  before_action :find_post, :only => [:show, :edit, :update, :destroy, :fake_delete, :posts_of_this_user]

  def index
    @posts = Post.where("forum_id is NULL").where("status = ? OR status = ? AND user_id = ?", 'public', 'private', session[:user_id]).order("updated_at DESC")
    #@public_posts = Post.where(status: 'public')
    #@private_posts = Post.where(status: 'private')
    #             .where(user_id: session[:user_id])
    #@posts = @public_posts + @private_posts
    #@posts.sort!{ |a, b| b.updated_at <=> a.updated_at }
    
    # 在 sql, 'AND' 優先於 'OR'
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params
    @post.user_id = (session[:user_id] || 1)
    # user with id 1 is for guest if any accident

    if @post.save
      flash[:notice] = "新增文章成功"
      redirect_to posts_path #@post
    else
      flash[:alert] = "新增文章失敗"
      render :new
    end
  end

  def edit
    if @post.user_id != session[:user_id]
      flash[:alert] = "你不能編輯這篇文章唷 o'_'o"
      redirect_to @post
    end
  end

  def update
    if @post.update post_params
      flash[:notice] = "編輯文章成功"
      redirect_to @post
    else
      flash[:alert] = "編輯文章失敗"
      render :edit
    end
  end

  # 需增加是否為author的判斷
  def destroy
    PostTagship.where(:post_id => @post).delete_all
    if @post.destroy
      flash[:notice] = "刪除文章成功"
      redirect_to posts_path
    end
  end

  # update status to 'deleted', server keeps this post in case
  def fake_delete
    if @post.user_id == session[:user_id]
      @post.status = "deleted"
      @post.save
      redirect_to user_posts_path(@post.user)
    else
      flash[:alert] = "you can't delete this post"
      redirect_to @post
    end
  end

  protected

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :user_id, :status, :forum_id, :tag_ids => [])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
end

app/helpers/forums_helper.rb
module ForumsHelper

  def action_link
    find_ship
    case @ship.try(:status)
    when "hosting"
      content_tag :a, link_to("編輯看板", edit_forum_path(@forum))
    when "joined"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    when "pending"
      content_tag :a, link_to("取消申請", cancel_forum_path(@forum))
    when "bucketed"
      content_tag :a, link_to("退出看板", leave_forum_path(@forum))
    else
      content_tag :a, link_to("加入看板", join_forum_path(@forum))
    end
  end

  def members_wanna_join
    content_tag :a, link_to("誰想加入", check_join_form_path(@forum))
  end

  def post_a_feiwen_link
    find_ship
    if @ship.try(:status) == "hosting" || @ship.try(:status) == "joined"
      content_tag :a, link_to("po 個費文", new_forum_post_path(@forum))
    end
  end

  protected

  def find_ship
    @ship = ForumUsership.find_by_forum_id_and_user_id(@forum, current_user)
  end
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_li text, path
    active = request.path == path ? "active" : ""
    content_tag :li, link_to(text, path), class: active + " navbar-nav"
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_replys_helper.rb
module PostReplysHelper
end

app/helpers/post_status_helper.rb
module PostStatusHelper
  def post_status_signal post
    case post.status
    when "public"
      return "+"
    when "private"
      return "-"
    end
  end
end

app/helpers/post_tags_helper.rb
module PostTagsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/helpers/userlink_helper.rb
module UserlinkHelper
  def user_link post, userid
    username = post.user.try(:name)
    userid ||= -1
    content_tag :a, link_to(username, userid)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<%= form_for post do |f| %>
  <%= f.label :title, "標題: " %><br>
  <%= f.text_field :title, placeholder: "what's on your mind?" %><br>
  <%= f.label :content, "內容: " %><br>
  <%= f.text_area :content %><br>
  <span>
    <span class="glyphicon glyphicon-tags"></span>
  </span>&nbsp
  <%= f.label :tag_ids, "標籤: " %><br>
  <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>
  <%= f.label :status, "status: " %><br>  
  <%= f.select :status, Post.where("status = ? OR status = ?", "public", "private").uniq.pluck(:status) %>
  <%= f.submit "送出" %>
<% end %>

app/views/posts/_new_form.html.erb
<%= form_for post do |f| %>
  <%= f.label :title, "標題: " %><br>
  <%= f.text_field :title %><br>
  <%= f.label :content, "內容: " %><br>
  <%= f.text_area :content %><br>
  <%#= f.label :user_id, "名字: " %><br>
  <%#= f.collection_select :user_id, User.all, :id, :name %><br>
  <span>
    <span class="glyphicon glyphicon-tags"></span>
  </span>&nbsp
  <%= f.label :tag_ids, "標籤: " %><br>
  <%= f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>
  <%= f.label :status, "status: " %><br>  
  <%= f.select :status, Post.where("status != ?", "deleted").uniq.pluck(:status) %>
  <%= f.submit "送出" %>
<% end %>

app/views/posts/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    編輯文章
  </div>
  <div class="panel-body">
    <%= render 'form', :post => Post.find(params[:id]) %>
  </div>
</div>

<%#= form_for @post do |f| %>
  <%#= f.text_field :title %>
  <%#= f.text_area :content %>
  <%#= f.submit %>
<%# end %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
  <div class="panel panel-primary">
    <div class="panel-heading">
        <%= current_user.name %>:
    </div>

    <div class="panel-body">
      <%= render "form", :post => Post.new %>
    </div>
  </div>
<% end %>

<!--<h2>文章列表 (public posts)</h2>-->

<% @posts.each do |post| %>
  <div class="panel panel-default">

    <div class="panel-heading">
      <%= link_to post.title, post_path(post) %>
      <%#= post.updated_at.to_formatted_s(:short) %>
      <%= distance_of_time_in_words(post.updated_at, Time.now) %>
      <% if post.forum %>
        <%= link_to post.forum.name, forum_posts_path(post.forum) %>
      <% end %>
    </div>

    <div class="panel-body">
      <%= user_link post, user_posts_path(post.user) %>:
      <%= post.content %>
      <hr>

      <div>
        <span class="glyphicon glyphicon-tags"></span>
        &nbsp
        <% post.tags.each do |tag| %>
          <%= link_to "• #{tag.name}", posts_tag_path(tag) %>
        <% end %>
      </div>
    </div>

    <% if user_signed_in? %>  
      <div class="panel-footer">
        <%= render 'post_replies/reply', :post => post %>
        <div class="row-fluid">
          
          <div class="">
            <%= current_user.name %>:
          </div>

          <div class="">
            <%= form_for post.replies.create, :url => post_replies_path(post) do |f| %>
              <%= f.text_field :content, placeholder: "write a comment..." %>
              <%= f.submit "submit", :style => "display: none" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    
  </div>
<% end %>

app/views/posts/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    新增文章
  </div>
  <div class="panel-body">
    <%= render 'form', :post => Post.new %>
  </div>
</div>

<%#= form_for @post do |f| %>
  <%#= f.text_field :title %>
  <%#= f.text_area :content %>
  <%#= f.submit %>
<%# end %>
<%#= form_tag posts_path do %>
  <%#= text_field_tag :title %>
  <%#= text_area_tag :content %>
  <!--<input type='submit'>-->
<%# end %>

app/views/posts/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @post.title %>
    <% if @post.forum %>
      <%= link_to @post.forum.name, forum_posts_path(@post.forum) %>
    <% end %>
  </div>

  <div class="panel-body">
    <%= @post.content %><br>
    by
    <%= @post.user.try(:name) %>
    <hr>
    
    <%= render 'post_replies/reply', :post => @post %>
    <hr>

    <span>
      <span class="glyphicon glyphicon-tags"></span>
    </span>&nbsp
    <% @post.tags.each do |tag| %>
      <%= link_to "• #{tag.name}", posts_tag_path(tag) %>
    <% end %>

  </div>
  <div class="panel-footer">
    <%= link_to '新增標籤', new_post_tag_path(@post) %>
    <%= link_to '編輯', edit_post_path(@post) %>
    <%= link_to '刪除', fake_delete_post_path(@post), method: :put, :data => {confirm: "你確定嗎?"} %>
    <%#= link_to '真刪除', @post, method: :delete, :data => {:confirm => "你確定嗎?"} %>
  </div>
</div>